#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

CONF="/etc/freeradius3"
INIT="/etc/init.d/radiusd"
NAME="radius_manager"


. /lib/functions.sh
config_load radius_manager

config_get PASSWORD_METHOD general password_storage "ntlm"

generate_password()
{
	generate_${PASSWORD_METHOD}_password "$1"
}

generate_clear_password()
{
	echo "Cleartext-Password := \"$1\""
}

generate_bcrypt_password()
{
	python3 -c "import bcrypt; print('Crypt-Password := \"' + bcrypt.hashpw(b'$1', bcrypt.gensalt()).decode() + '\"')"
}

generate_ntlm_password()
{
	python3 -c "import hashlib; print('NT-Password := \"' + hashlib.new('md4', '$1'.encode('utf-16le')).hexdigest().upper() + '\"')"
}

clear_password()
{
	echo "Clearing password for $1"
	uci -q delete $NAME.$1.clear_password
	uci -q delete $NAME.$1.bcrypt_password
	uci -q delete $NAME.$1.ntlm_password
}

set_password()
{
	clear_password $1
	uci set $NAME.$1.${PASSWORD_METHOD}_password="$2"
}

keep_password()
{
	config_get password $1 clear_password
	[ ! -z "$password" ] && echo "Cleartext-Password := \"$password\"" && return
	config_get crypt_password $1 crypt_password
	[ ! -z "$crypt_password" ] && echo "Crypt-Password := \"$crypt_password\"" && return
	config_get ntlm_password $1 ntlm_password
	[ ! -z "$ntlm_password" ] && echo "NT-Password := \"$ntlm_password\"" && return
	echo ""
}

rebuild()
{
	clear_configure
	config_foreach append_client client
	config_foreach append_user user
	config_foreach append_realm_format realm_format
	config_foreach append_realm realm
	config_foreach append_server server
	reload_radiusd
}

clear_configure()
{
	#sed '#^$INCLUDE /etc/radius_manager/authorize.extra #d' /etc/freeradius3/mods-config/files/authorize
	echo > $CONF/clients.extra
	echo > $CONF/authorize.extra
	echo > $CONF/realm.extra
	echo > $CONF/proxy.extra
}

append_realm_format()
{
	local name type delimiter
	config_get name $1 name
	config_get type $1 type
	config_get delimiter $1 delimiter
	config_get enabled $1 enabled "0"
	if [ "$enabled" -eq "1" ] ; then

	cat <<-EOF >>$CONF/realm.extra
realm $name {
	format = $type
	delimiter = $delimiter
}
EOF
	else
	
	cat <<-EOF >>$CONF/realm.extra
#realm $name {
#	format = $type
#	delimiter = $delimiter
#}
EOF
	fi
}

generate_proxy_realm()
{
	local match nostrip target
	match=$1
	nostrip=$2
	target=$3
	echo -e "realm $match {"
	echo -e "\tnostrip = $nostrip"
	[ -z "$target" ] && echo -e "\tpool = LOCAL"
	echo -e "}"

}

append_realm()
{
	local name match nostrip target
	name=$1
	config_get match $1 match
	config_get_bool nostrip $1 nostrip false
	config_get target $1 target
	cat <(generate_proxy_realm "$match" "$nostrip" "$target") >>$CONF/proxy.extra
}

generate_server()
{
	local name host port secret type
	name=$1
	host=$2
	port=$3
	secret=$4
	type=$5

	echo -e "home_server $name {"
	echo -e "\taddress = $host"
	echo -e "\tport = $port"
	echo -e "\tsecret = $secret"
	echo -e "\ttype = $type"
	echo -e "}"
	echo -e "home_server_pool $name {"
	echo -e "\ttype = fail-over"
	echo -e "\thome_server = $name"
	echo -e "}"
}

append_server()
{
	local name host port secret type
	config_get name $1 name
	config_get host $1 host
	config_get port $1 port
	config_get secret $1 secret
	config_get type $1 type

	cat <(generate_server "$name" "$host" "$port" "$secret" "$type") >>$CONF/proxy.extra
}

append_client()
{
	local name ipaddr secret
	config_get name $1 name
	config_get ipaddr $1 ipaddr
	config_get secret $1 secret

	cat <<-EOF >>$CONF/clients.extra
client $name {
	secret = $secret
	ipaddr = $ipaddr
	shortname = $name
}
EOF
}

generate_vlan_attributes()
{
	local vlan
	vlan=$1
	if [ ! -z "$vlan" ] ; then
		echo -e "\tTunnel-Type = \"VLAN\","
		echo -e "\tTunnel-Medium-Type = \"IEEE-802\","
		echo -e "\tTunnel-Private-Group-Id = \"$vlan\""
	fi
}

append_user()
{
	local username password rad_password
	username=$1
	config_get password $1 password
	config_get_bool vlans_enabled $1 vlans_enabled false

	if [ -z "$password" ]; then
		config_get rad_password $1 rad_password ""
	else
		rad_password=$(generate_password "$password")
	fi
	echo -e "$username\t$rad_password" >>$CONF/authorize.extra
	if [ "$vlans_enabled" = "1" ] ; then
		config_get vlan $1 vlan
		cat <(generate_vlan_attributes $vlan) >>$CONF/authorize.extra
	fi
    [ -z "$password" ] && return
	uci -q delete $NAME.$1.password
	uci set $NAME.$1.rad_password="$rad_password"
	uci set $NAME.$1.password_type="$PASSWORD_METHOD"
	uci set $NAME.$1.password_updated="$(date "+%Y/%m/%d-%H:%M:%S")"
	uci commit $NAME
}

start_service() {
	# Not a real service, just rebuild config
	rebuild
	$INIT start
}

stop_service() {
	$INIT stop
}

reload_service() {
	# Called when config changes
	rebuild
	$INIT restart
}

service_triggers() {
	# Register procd trigger to rebuild when radius_manager config changes
	procd_add_reload_trigger "radius_manager"
}
